language: r
cache: packages
sudo: true
warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libgit2-dev

matrix:
  include:
  - r: oldrel
  - r: release
    deploy:
      provider: script
      script:
        - bash data-raw/deploy.sh
      skip_cleanup: true
      on:
        branch: develop
  - r: devel
