language: r
cache: packages
sudo: true
warnings_are_errors: false

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libgit2-dev

matrix:
  include:
  - r: oldrel
  - r: release
    deploy:
      provider: script
      script:
        - bash data-raw/update_datasets.sh
      skip_cleanup: true
      on:
        all_branches: true
  - r: devel
